import React from 'react';
import { ShieldCheckIcon, PriceTagIcon, ClockIcon, HeadsetIcon } from './components/icons/FeatureIcons';
import { TimeSlot, LocalizedString, VendorSubscription, CustomerSubscription } from './types';

export const TEXTS = {
  header: {
    services: { en: 'Services', bn: 'সেবাসমূহ' },
    about: { en: 'About Us', bn: 'আমাদের সম্পর্কে' },
    contact: { en: 'Contact', bn: 'যোগাযোগ' },
    myAccount: { en: 'My Account', bn: 'আমার অ্যাকাউন্ট' },
    loginSignUp: { en: 'My Account', bn: 'আমার অ্যাকাউন্ট' },
    logout: { en: 'Logout', bn: 'লগআউট' },
    forProfessionals: { en: 'For Professionals', bn: 'পেশাদারদের জন্য' },
  },
  hero: {
    title: { en: 'Your Home, Expertly Cared For.', bn: 'আপনার বাসা, আমাদের যত্ন।' },
    subtitle: { en: 'Book trusted & verified local professionals for any home service.', bn: 'যেকোনো হোম সার্ভিসের জন্য বিশ্বস্ত এবং যাচাইকৃত স্থানীয় পেশাদারদের বুক করুন।' },
    searchPlaceholder: { en: 'What service do you need? (e.g., AC Cleaning)', bn: 'আপনার কোন পরিষেবা প্রয়োজন? (যেমন, এসি ক্লিনিং)' },
    searchButton: { en: 'Find Professionals', bn: 'কর্মী খুঁজুন' },
  },
  services: {
    title: { en: 'Popular Services', bn: 'জনপ্রিয় সেবাসমূহ' },
  },
  plusBanner: {
    title: { en: 'Unlock Exclusive Benefits with FixBD Plus!', bn: 'FixBD Plus-এর সাথে এক্সক্লুসিভ সুবিধা আনলক করুন!' },
    subtitle: { en: 'Save on every service, get priority support, and enjoy peace of mind with our premium subscription.', bn: 'প্রতিটি পরিষেবাতে সঞ্চয় করুন, অগ্রাধিকার সমর্থন পান এবং আমাদের প্রিমিয়াম সাবস্ক্রিপশন সহ মানসিক শান্তি উপভোগ করুন।' },
    learnMore: { en: 'Learn More', bn: 'আরও জানুন' },
  },
  howItWorks: {
    title: { en: 'Get Help in 3 Easy Steps', bn: '৩টি সহজ ধাপে সহায়তা পান' },
    step1Title: { en: 'Book Your Service', bn: 'আপনার সার্ভিস বুক করুন' },
    step1Desc: { en: 'Select the service you need and tell us your preferred time.', bn: 'আপনার প্রয়োজনীয় পরিষেবাটি নির্বাচন করুন এবং আপনার পছন্দের সময় আমাদের জানান।' },
    step2Title: { en: 'Get a Verified Pro', bn: 'যাচাইকৃত প্রো পান' },
    step2Desc: { en: 'We match you with a skilled and background-checked professional.', bn: 'আমরা আপনাকে একজন দক্ষ এবং ব্যাকগ্রাউন্ড-চেক করা পেশাদারের সাথে মিলিয়ে দেই।' },
    step3Title: { en: 'Relax & Rate', bn: 'আরাম করুন ও রেট দিন' },
    step3Desc: { en: 'Your pro gets the job done right. Pay securely and leave a review.', bn: 'আপনার প্রো কাজটি সঠিকভাবে সম্পন্ন করবে। নিরাপদে অর্থ প্রদান করুন এবং একটি পর্যালোচনা দিন।' },
  },
  whyChooseUs: {
    title: { en: 'Peace of Mind, Guaranteed.', bn: 'মনের শান্তি, নিশ্চিত।' },
    subtitle: { en: 'We are committed to providing you with a safe, reliable, and high-quality service experience, every single time.', bn: 'আমরা প্রতিবার আপনাকে একটি নিরাপদ, নির্ভরযোগ্য এবং উচ্চ-মানের পরিষেবা অভিজ্ঞতা প্রদান করতে প্রতিশ্রুতিবদ্ধ।' },
  },
  testimonials: {
    title: { en: 'What Our Customers Say', bn: 'আমাদের গ্রাহকরা যা বলেন' },
  },
  footer: {
    about: { en: 'FixBD is your one-stop solution for all home service needs in Bangladesh. We connect you with trusted, skilled, and verified professionals.', bn: 'FixBD বাংলাদেশে আপনার সমস্ত হোম সার্ভিস চাহিদার একটি ওয়ান-স্টপ সমাধান। আমরা আপনাকে বিশ্বস্ত, দক্ষ এবং যাচাইকৃত পেশাদারদের সাথে সংযুক্ত করি।' },
    quickLinks: { en: 'Quick Links', bn: 'দ্রুত লিঙ্ক' },
    legal: { en: 'Legal', bn: 'আইনি' },
    terms: { en: 'Terms of Service', bn: 'পরিষেবার শর্তাবলী' },
    privacy: { en: 'Privacy Policy', bn: 'গোপনীয়তা নীতি' },
    followUs: { en: 'Follow Us', bn: 'আমাদের অনুসরণ করুন' },
    copyright: { en: '© 2024 FixBD. All rights reserved.', bn: '© ২০২৪ FixBD. সর্বস্বত্ব সংরক্ষিত।' },
    adminPanel: { en: 'Admin Panel', bn: 'অ্যাডমিন প্যানেল' },
    moderatorLogin: { en: 'Moderator Login', bn: 'মডারেটর লগইন' },
  },
  bottomNav: {
    home: { en: 'Home', bn: 'হোম' },
    services: { en: 'Services', bn: 'সেবা' },
    joinUs: { en: 'Join Us', bn: 'যোগ দিন' },
    account: { en: 'Account', bn: 'অ্যাকাউন্ট' },
  },
  vendorBottomNav: {
    jobs: { en: 'Jobs', bn: 'কাজ' },
    history: { en: 'History', bn: 'হিস্টোরি' },
    profile: { en: 'Profile', bn: 'প্রোফাইল' },
    withdraw: { en: 'Withdraw', bn: 'উত্তোলন' },
  },
  servicePage: {
    allServices: { en: 'All Services', bn: 'সকল সেবা' },
    description: { en: 'Service Description', bn: 'সেবার বিবরণ' },
    availablePackages: { en: 'Available Packages', bn: 'উপলব্ধ প্যাকেজ' },
    book: { en: 'Book', bn: 'বুক' },
  },
  bookingFlow: {
    title: { en: 'Book Service', bn: 'সার্ভিস বুক করুন' },
    step1: { en: 'Select Date & Time', bn: 'তারিখ ও সময় নির্বাচন করুন' },
    step2: { en: 'Review & Confirm', bn: 'পর্যালোচনা ও নিশ্চিত করুন' },
    orderSummary: { en: 'Order Summary', bn: 'অর্ডার সারসংক্ষেপ' },
    yourDetails: { en: 'Your Details', bn: 'আপনার বিবরণ' },
    selectDate: { en: 'Select a Date', bn: 'একটি তারিখ নির্বাচন করুন' },
    selectTime: { en: 'Select a Time Slot', bn: 'একটি সময় স্লট নির্বাচন করুন' },
    addressPlaceholder: { en: 'Enter your full address', bn: 'আপনার সম্পূর্ণ ঠিকানা লিখুন' },
    selectAddress: { en: 'Select your area', bn: 'আপনার এলাকা নির্বাচন করুন' },
    phonePlaceholder: { en: 'Enter your mobile number', bn: 'আপনার মোবাইল নম্বর লিখুন' },
    service: { en: 'Service', bn: 'সেবা' },
    package: { en: 'Package', bn: 'প্যাকেজ' },
    date: { en: 'Date', bn: 'তারিখ' },
    time: { en: 'Time', bn: 'সময়' },
    address: { en: 'Address', bn: 'ঠিকানা' },
    phone: { en: 'Phone', bn: 'ফোন' },
    back: { en: 'Back', bn: 'ফিরে যান' },
    next: { en: 'Next', bn: 'পরবর্তী' },
    confirmBooking: { en: 'Confirm Booking', bn: 'বুকিং নিশ্চিত করুন' },
    plusMember: { en: 'Plus Member Discount', bn: 'প্লাস সদস্য ছাড়' },
    total: { en: 'Total Payable', bn: 'সর্বমোট প্রদেয়' },
    noVendorForSlot: { en: 'Sorry, no professionals are available for this service in your area at the selected time.', bn: 'দুঃখিত, আপনার নির্বাচিত সময়ে এই এলাকায় এই পরিষেবার জন্য কোনো পেশাদার উপলব্ধ নেই।' },
  },
  confirmationPage: {
    title: { en: 'Booking Confirmed!', bn: 'বুকিং নিশ্চিত হয়েছে!' },
    subtitle: { en: 'Thank you! Your service request has been received. Our professional will contact you shortly.', bn: 'ধন্যবাদ! আপনার পরিষেবা অনুরোধটি গৃহীত হয়েছে। আমাদের পেশাদার শীঘ্রই আপনার সাথে যোগাযোগ করবে।' },
    bookingId: { en: 'Booking ID', bn: 'বুকিং আইডি' },
    summaryTitle: { en: 'Booking Summary', bn: 'বুকিং সারসংক্ষেপ' },
    providerTitle: { en: 'Your Assigned Professional', bn: 'আপনার নির্ধারিত পেশাদার' },
    rating: { en: 'Rating', bn: 'রেটিং' },
    done: { en: 'Done', bn: 'সম্পন্ন' },
    totalPaid: { en: 'Total Paid', bn: 'সর্বমোট পরিশোধিত' },
    trackBooking: { en: 'Track My Booking', bn: 'আমার বুকিং ট্র্যাক করুন' },
  },
  vendorDashboard: {
    dashboard: { en: 'My Dashboard', bn: 'আমার ড্যাশবোর্ড' },
    logout: { en: 'Exit Vendor View', bn: 'ভেন্ডর ভিউ থেকে প্রস্থান' },
    welcome: { en: 'Welcome back', bn: 'স্বাগতম' },
    
    newJobs: { en: 'New Jobs', bn: 'নতুন কাজ' },
    ongoingJobs: { en: 'Ongoing Jobs', bn: 'চলমান কাজ' },
    serviceHistory: { en: 'Service History', bn: 'পরিষেবার ইতিহাস' },
    myProfile: { en: 'My Profile', bn: 'আমার প্রোফাইল' },
    
    noNewJobs: { en: 'No new jobs assigned right now.', bn: 'এখন কোনো নতুন কাজ অ্যাসাইন করা নেই।' },
    noOngoingJobs: { en: 'No jobs are currently in progress.', bn: 'বর্তমানে কোনো কাজ চলছে না।' },
    noPastJobs: { en: 'Your past jobs will appear here.', bn: 'আপনার অতীতের কাজগুলো এখানে দেখা যাবে।' },
    
    manageWorkingHours: { en: 'Manage Working Hours', bn: 'কাজের সময় পরিচালনা' },
    withdrawEarnings: { en: 'Withdraw Earnings', bn: 'আয় উত্তোলন' },
    
    customerInfo: { en: 'Customer Info', bn: 'গ্রাহকের তথ্য' },
    
    startJob: { en: 'Start Job', bn: 'কাজ শুরু করুন' },
    reportDelay: { en: 'Report Delay', bn: 'বিলম্ব রিপোর্ট করুন' },
    markComplete: { en: 'Mark as Complete', bn: 'সম্পন্ন হিসেবে চিহ্নিত করুন' },
    
    delayReason: { en: 'Reason for Delay', bn: 'বিলম্বের কারণ' },
    heavyTraffic: { en: 'Heavy Traffic', bn: 'ভারী ট্র্যাফিক' },
    previousJobDelayed: { en: 'Previous Job Delayed', bn: 'পূর্ববর্তী কাজ বিলম্বিত' },
    other: { en: 'Other', bn: 'অন্যান্য' },
    estimatedDelay: { en: 'Estimated Delay (minutes)', bn: 'আনুমানিক বিলম্ব (মিনিট)' },
    submitDelay: { en: 'Submit Delay Report', bn: 'বিলম্ব রিপোর্ট জমা দিন' },
    
    uploadPhotosTitle: { en: 'Upload Job Photos', bn: 'কাজের ছবি আপলোড করুন' },
    uploadPhotosDesc: { en: 'Upload before and after photos to complete the job.', bn: 'কাজটি সম্পন্ন করতে আগে এবং পরের ছবি আপলোড করুন।' },
    before: { en: 'Before', bn: 'আগে' },
    after: { en: 'After', bn: 'পরে' },
    submitAndComplete: { en: 'Submit & Complete Job', bn: 'জমা দিন ও কাজ সম্পন্ন করুন' },
    
    workingHoursDesc: { en: 'Set the days and times you are available to work.', bn: 'আপনি কাজ করার জন্য উপলব্ধ দিন এবং সময় সেট করুন।' },
    saveChanges: { en: 'Save Changes', bn: 'পরিবর্তন সংরক্ষণ করুন' },
    cancel: { en: 'Cancel', bn: 'বাতিল'},
    
    earningsSummary: { en: 'Earnings Summary', bn: 'আয় সারসংক্ষেপ' },
    totalEarnings: { en: 'Total Earnings', bn: 'মোট আয়' },
    pendingBalance: { en: 'Pending Balance', bn: 'অমীমাংসিত ব্যালেন্স' },
    lastMonth: { en: 'Last Month', bn: 'গত মাস' },
    currentPlan: { en: 'Your Current Plan', bn: 'আপনার বর্তমান প্ল্যান' },
    commission: { en: 'Commission', bn: 'কমিশন' },
    upgradeToPro: { en: 'Upgrade to Pro', bn: 'প্রো-তে আপগ্রেড করুন' },

    statusAvailable: { en: 'Available', bn: 'উপলব্ধ' },
    statusBusy: { en: 'Busy', bn: 'ব্যস্ত' },
    statusOffline: { en: 'Offline', bn: 'অফলাইন' },
    goOnline: { en: 'Go Online', bn: 'অনলাইন হোন' },
    goOffline: { en: 'Go Offline', bn: 'অফলাইন হোন' },
    
    withdrawToBkash: { en: 'Withdraw to bKash', bn: 'বিকাশে উত্তোলন' },
    availableForWithdrawal: { en: 'Available for Withdrawal', bn: 'উত্তোলনের জন্য উপলব্ধ' },
    amount: { en: 'Amount', bn: 'পরিমাণ' },
    bKashNumber: { en: 'bKash Number', bn: 'বিকাশ নম্বর' },
    confirmWithdrawal: { en: 'Confirm Withdrawal', bn: 'উত্তোলন নিশ্চিত করুন' },
    withdrawalHistory: { en: 'Withdrawal History', bn: 'উত্তোলনের ইতিহাস' },
    noWithdrawals: { en: 'No withdrawal history found.', bn: 'কোনো উত্তোলনের ইতিহাস পাওয়া যায়নি।' },
    
    autoAcceptLabel: { en: 'Auto-Accept New Jobs', bn: 'নতুন কাজ স্বয়ংক্রিয়ভাবে গ্রহণ করুন' },
  },
  customerDashboard: {
    welcome: { en: 'Welcome back', bn: 'স্বাগতম' },
    bookNewService: { en: 'Book a New Service', bn: 'নতুন পরিষেবা বুক করুন' },
    myUpcomingVisits: { en: 'My Upcoming Visits', bn: 'আমার আসন্ন ভিজিট'},
    noUpcomingBookings: { en: 'No upcoming visits. Ready for a new service?', bn: 'কোনো আসন্ন ভিজিট নেই। নতুন পরিষেবা নিতে প্রস্তুত?' },
    trackService: { en: 'Track Service', bn: 'পরিষেবা ট্র্যাক করুন' },
    recentServices: { en: 'Recent Services', bn: 'সাম্প্রতিক পরিষেবাসমূহ' },
    noRecentServices: { en: 'Your past services will appear here.', bn: 'আপনার অতীতের পরিষেবাগুলি এখানে দেখা যাবে।' },
    bookAgain: { en: 'Book Again', bn: 'আবার বুক করুন' },
    rateExperience: { en: 'Rate Your Experience', bn: 'আপনার অভিজ্ঞতা রেট দিন' },
    viewDetails: { en: 'View Details', bn: 'বিবরণ দেখুন' },
    myInfo: { en: 'My Info', bn: 'আমার তথ্য' },
    editInfo: { en: 'Edit Info', bn: 'তথ্য সম্পাদনা' },
    saveInfo: { en: 'Save', bn: 'সংরক্ষণ' },
    cancelEdit: { en: 'Cancel', bn: 'বাতিল' },
    logout: { en: 'Logout', bn: 'লগআউট' },
    rateService: { en: 'Rate Service', bn: 'পরিষেবা রেট করুন' },
    viewPhotos: { en: 'View Photos', bn: 'ছবি দেখুন' },
    trackBooking: { en: 'Track Booking', bn: 'বুকিং ট্র্যাক করুন' },
    jobPhotos: { en: 'Job Photos', bn: 'কাজের ছবি' },
    ratingTitle: { en: 'Rate Your Service with', bn: 'আপনার পরিষেবা রেট করুন' },
    howWasService: { en: 'How was your experience?', bn: 'আপনার অভিজ্ঞতা কেমন ছিল?' },
    leaveReviewPlaceholder: { en: 'Tell us more about your experience (optional)', bn: 'আপনার অভিজ্ঞতা সম্পর্কে আরও বলুন (ঐচ্ছিক)' },
    submitRating: { en: 'Submit Rating', bn: 'রেটিং জমা দিন' },
    delayAlert: { en: 'Running late due to', bn: 'কারণে দেরি হচ্ছে' },
    liveChat: { en: 'Live Chat with Support', bn: 'সাপোর্টের সাথে লাইভ চ্যাট' },
  },
  adminDashboard: {
    dashboard: { en: 'Dashboard', bn: 'ড্যাশবোর্ড' },
    users: { en: 'Users', bn: 'ব্যবহারকারী' },
    vendors: { en: 'Vendors', bn: 'ভেন্ডর' },
    moderators: { en: 'Moderators', bn: 'মডারেটর' },
    bookings: { en: 'Bookings', bn: 'বুকিং' },
    finance: { en: 'Finance', bn: 'অর্থ' },
    subscriptions: { en: 'Subscriptions', bn: 'সাবস্ক্রিপশন' },
    services: { en: 'Services', bn: 'সেবাসমূহ' },
    locations: { en: 'Locations', bn: 'এলাকা' },
    logout: { en: 'Exit Admin View', bn: 'অ্যাডমিন ভিউ থেকে প্রস্থান' },
    overview: { en: 'Platform Overview', bn: 'প্ল্যাটফর্ম ওভারভিউ' },
    totalUsers: { en: 'Total Users', bn: 'মোট ব্যবহারকারী' },
    totalVendors: { en: 'Total Vendors', bn: 'মোট ভেন্ডর' },
    totalRevenue: { en: 'Total Revenue', bn: 'মোট রাজস্ব' },
    pendingApplications: { en: 'Pending Applications', bn: 'অপেক্ষমাণ আবেদন' },
    recentBookings: { en: 'Recent Bookings', bn: 'সাম্প্রতিক বুকিং' },
    userManagement: { en: 'User Management', bn: 'ব্যবহারকারী ব্যবস্থাপনা' },
    vendorManagement: { en: 'Vendor Management', bn: 'ভেন্ডর ব্যবস্থাপনা' },
    approvedVendors: { en: 'Approved Vendors', bn: 'অনুমোদিত ভেন্ডর' },
    vendorApplications: { en: 'Vendor Applications', bn: 'ভেন্ডর আবেদন' },
    reviewApplication: { en: 'Review Application', bn: 'আবেদন পর্যালোচনা' },
    approve: { en: 'Approve', bn: 'অনুমোদন' },
    reject: { en: 'Reject', bn: 'প্রত্যাখ্যান' },
    viewCV: { en: 'View CV', bn: 'সিভি দেখুন' },
    viewNID: { en: 'View NID', bn: 'এনআইডি দেখুন' },
    viewPhotos: { en: 'View Photos', bn: 'ছবি দেখুন' },
    bookingManagement: { en: 'Booking Management', bn: 'বুকিং ব্যবস্থাপনা' },
    financialOverview: { en: 'Financial Overview', bn: 'আর্থিক ওভারভিউ' },
    totalCommission: { en: 'Total Commission', bn: 'মোট কমিশন' },
    subscriptionRevenue: { en: 'Subscription Revenue', bn: 'সাবস্ক্রিপশন রাজস্ব' },
    subscriptionPlans: { en: 'Subscription Plans', bn: 'সাবস্ক্রিপশন প্ল্যান' },
    activeSubscribers: { en: 'Active Subscribers', bn: 'সক্রিয় গ্রাহক' },
    serviceManagement: { en: 'Service Management', bn: 'সেবা ব্যবস্থাপনা' },
    addNewService: { en: 'Add New Service', bn: 'নতুন সেবা যোগ করুন' },
    editService: { en: 'Edit Service', bn: 'সেবা সম্পাদনা' },
    managePackages: { en: 'Manage Packages', bn: 'প্যাকেজ পরিচালনা' },
    deleteService: { en: 'Delete Service', bn: 'সেবা মুছুন' },
    addNewPackage: { en: 'Add New Package', bn: 'নতুন প্যাকেজ যোগ করুন' },
    editPackage: { en: 'Edit Package', bn: 'প্যাকেজ সম্পাদনা' },
    deletePackage: { en: 'Delete Package', bn: 'প্যাকেজ মুছুন' },
    serviceNameEn: { en: 'Service Name (EN)', bn: 'সেবার নাম (EN)' },
    serviceNameBn: { en: 'Service Name (BN)', bn: 'সেবার নাম (BN)' },
    descriptionEn: { en: 'Description (EN)', bn: 'বিবরণ (EN)' },
    descriptionBn: { en: 'Description (BN)', bn: 'বিবরণ (BN)' },
    heroImageUrl: { en: 'Hero Image URL', bn: 'হিরো ইমেজ URL' },
    icon: { en: 'Icon', bn: 'আইকন' },
    packageNameEn: { en: 'Package Name (EN)', bn: 'প্যাকেজের নাম (EN)' },
    packageNameBn: { en: 'Package Name (BN)', bn: 'প্যাকেজের নাম (BN)' },
    priceRangeEn: { en: 'Price Range (EN, e.g., ৳600 – ৳800)', bn: 'মূল্য পরিসীমা (EN, যেমন, ৳৬০০ – ৳৮০০)' },
    priceRangeBn: { en: 'Price Range (BN, e.g., ৳৬০০ – ৳৮০০)', bn: 'মূল্য পরিসীমা (BN, যেমন, ৳৬০০ – ৳৮০০)' },
    basePrice: { en: 'Base Price (e.g., 600)', bn: 'आधार মূল্য (যেমন, ৬০০)' },
    durationEn: { en: 'Duration (EN, e.g., 45-60 min)', bn: 'সময়কাল (EN, যেমন, ৪৫-৬০ মিনিট)' },
    durationBn: { en: 'Duration (BN, e.g., ৪৫-৬০ মিনিট)', bn: 'সময়কাল (BN, যেমন, ৪৫-৬০ মিনিট)' },
    save: { en: 'Save', bn: 'সংরক্ষণ' },
    cancel: { en: 'Cancel', bn: 'বাতিল' },
    deleteConfirm: { en: 'Are you sure you want to delete this?', bn: 'আপনি কি নিশ্চিত যে আপনি এটি মুছে ফেলতে চান?' },
    delete: { en: 'Delete', bn: 'মুছে ফেলুন' },
    locationManagement: { en: 'Location Management', bn: 'এলাকা ব্যবস্থাপনা' },
    addNewArea: { en: 'Add New Area', bn: 'নতুন এলাকা যোগ করুন' },
    editArea: { en: 'Edit Area', bn: 'এলাকা সম্পাদনা' },
    areaNameEn: { en: 'Area Name (EN)', bn: 'এলাকার নাম (EN)' },
    areaNameBn: { en: 'Area Name (BN)', bn: 'এলাকার নাম (BN)' },
    manageAreas: { en: 'Manage Areas', bn: 'এলাকা পরিচালনা' },
    manageVendorAreasTitle: { en: 'Manage Service Areas for', bn: 'এর জন্য পরিষেবা এলাকা পরিচালনা করুন' },
    withdrawalRequests: { en: 'Withdrawal Requests', bn: 'উত্তোলন অনুরোধ' },
    markAsCompleted: { en: 'Mark as Completed', bn: 'সম্পন্ন হিসেবে চিহ্নিত করুন' },
    moderatorManagement: { en: 'Moderator Management', bn: 'মডারেটর ব্যবস্থাপনা' },
    moderatorAccounts: { en: 'Moderator Accounts', bn: 'মডারেটর অ্যাকাউন্ট' },
    activityLog: { en: 'Activity Log', bn: 'কার্যকলাপ লগ' },
    addModerator: { en: 'Add Moderator', bn: 'মডারেটর যোগ করুন' },
    removeModerator: { en: 'Remove Moderator', bn: 'মডারেটর সরান' },
    moderatorName: { en: 'Moderator Name', bn: 'মডারেটরের নাম' },
    email: { en: 'Email', bn: 'ইমেল' },
    password: { en: 'Password', bn: 'পাসওয়ার্ড' },
    remove: { en: 'Remove', bn: 'সরান' },
    removeConfirm: { en: 'Are you sure you want to remove this moderator?', bn: 'আপনি কি নিশ্চিত যে আপনি এই মডারেটরকে সরাতে চান?' },
    editProfile: { en: 'Edit Profile', bn: 'প্রোফাইল সম্পাদনা' },
    editVendorProfile: { en: 'Edit Vendor Profile', bn: 'ভেন্ডর প্রোফাইল সম্পাদনা' },
    editModeratorProfile: { en: 'Edit Moderator Profile', bn: 'মডারেটর প্রোফাইল সম্পাদনা' },
    phone: { en: 'Phone', bn: 'ফোন' },
    address: { en: 'Address', bn: 'ঠিকানা' },
    voterIdNumber: { en: 'Voter ID Number', bn: 'ভোটার আইডি নম্বর' },
    voterIdPhoto: { en: 'Voter ID Photo', bn: 'ভোটার আইডি ছবি' },
    uploadNewPhoto: { en: 'Upload New Photo', bn: 'নতুন ছবি আপলোড' },
  },
  moderatorLogin: {
    title: { en: 'Moderator Login', bn: 'মডারেটর লগইন' },
    emailPlaceholder: { en: 'Email Address', bn: 'ইমেল ঠিকানা' },
    passwordPlaceholder: { en: 'Password', bn: 'পাসওয়ার্ড' },
    login: { en: 'Login', bn: 'লগইন' },
    invalidCredentials: { en: 'Invalid email or password.', bn: 'অবৈধ ইমেল বা পাসওয়ার্ড।' },
  },
  moderatorDashboard: {
    operationsCenter: { en: 'Operations Center', bn: 'অপারেশন কেন্দ্র' },
    operations: { en: 'Operations', bn: 'অপারেশন' },
    vendors: { en: 'Vendors', bn: 'ভেন্ডর' },
    bookingsTitle: { en: 'All Bookings', bn: 'সমস্ত বুকিং' },
    filterByStatus: { en: 'Filter by Status', bn: 'স্ট্যাটাস দ্বারা ফিল্টার' },
    filterByArea: { en: 'Filter by Area', bn: 'এলাকা দ্বারা ফিল্টার' },
    allStatuses: { en: 'All Statuses', bn: 'সমস্ত স্ট্যাটাস' },
    allAreas: { en: 'All Areas', bn: 'সমস্ত এলাকা' },
    bookingId: { en: 'Booking ID', bn: 'বুকিং আইডি' },
    searchByBookingId: { en: 'Search by Booking ID...', bn: 'বুকিং আইডি দিয়ে খুঁজুন...' },
    customer: { en: 'Customer', bn: 'গ্রাহক' },
    service: { en: 'Service', bn: 'পরিষেবা' },
    location: { en: 'Location', bn: 'এলাকা' },
    assignedVendor: { en: 'Assigned Vendor', bn: 'নিযুক্ত ভেন্ডর' },
    status: { en: 'Status', bn: 'স্ট্যাটাস' },
    actions: { en: 'Actions', bn: 'কার্যকলাপ' },
    liveChatsTitle: { en: 'Live Chat Queue', bn: 'লাইভ চ্যাট কিউ' },
    logout: { en: 'Exit Moderator View', bn: 'মডারেটর ভিউ থেকে প্রস্থান' },
    noLiveChats: { en: 'No active or pending chats.', bn: 'কোনো সক্রিয় বা অপেক্ষমাণ চ্যাট নেই।' },
    assignVendor: { en: 'Assign Vendor', bn: 'ভেন্ডর অ্যাসাইন করুন' },
    assignVendorTitle: { en: 'Assign a Professional for', bn: 'এর জন্য একজন পেশাদার অ্যাসাইন করুন' },
    availableProfessionals: { en: 'Available Professionals for this Area & Skill', bn: 'এই এলাকা এবং দক্ষতার জন্য উপলব্ধ পেশাদার' },
    noAvailableVendors: { en: 'No vendors available with the required skill, in this area, at the moment.', bn: 'এই মুহূর্তে এই এলাকায় প্রয়োজনীয় দক্ষতা সহ কোনো ভেন্ডর উপলব্ধ নেই।' },
    confirmAssignment: { en: 'Confirm Assignment', bn: 'অ্যাসাইনমেন্ট নিশ্চিত করুন' },
    acceptChat: { en: 'Accept Chat', bn: 'চ্যাট গ্রহণ করুন' },
    viewDetails: { en: 'View Details', bn: 'বিবরণ দেখুন' },
    vendorDetails: { en: 'Vendor Details', bn: 'ভেন্ডরের বিবরণ' },
    contactInfo: { en: 'Contact Info', bn: 'যোগাযোগের তথ্য' },
    skills: { en: 'Skills', bn: 'দক্ষতা' },
    coverageArea: { en: 'Coverage Area', bn: 'পরিষেবা এলাকা' },
    weeklyAvailability: { en: 'Weekly Availability', bn: 'সাপ্তাহিক প্রাপ্যতা' },
    realtimeStatus: { en: 'Real-time Status', bn: 'রিয়েল-টাইম স্ট্যাটাস' },
  },
  liveChat: {
    title: { en: 'Live Support', bn: 'লাইভ সাপোর্ট' },
    welcome: { en: 'A support agent will be with you shortly.', bn: 'একজন সাপোর্ট এজেন্ট শীঘ্রই আপনার সাথে যুক্ত হবেন।' },
    inputPlaceholder: { en: 'Type your message...', bn: 'আপনার বার্তা টাইপ করুন...' },
    send: { en: 'Send', bn: 'পাঠান' },
  },
  vendorLanding: {
      title: { en: 'Join FixBD & Grow Your Business', bn: 'FixBD-তে যোগ দিন এবং আপনার ব্যবসা বাড়ান' },
      subtitle: { en: 'Connect with thousands of customers across Bangladesh and get a steady stream of job requests.', bn: 'বাংলাদেশ জুড়ে হাজার হাজার গ্রাহকদের সাথে সংযোগ স্থাপন করুন এবং নিয়মিত কাজের অনুরোধ পান।' },
      signUp: { en: 'Sign Up Now', bn: 'এখনই সাইন আপ করুন' },
      login: { en: 'Login to Dashboard', bn: 'ড্যাশবোর্ডে লগইন করুন' },
  },
  vendorSignUp: {
      title: { en: 'Become a FixBD Professional', bn: 'একজন FixBD পেশাদার হন' },
      step1: { en: 'Personal Info', bn: 'ব্যক্তিগত তথ্য' },
      step2: { en: 'Skills & Area', bn: 'দক্ষতা ও এলাকা' },
      step3: { en: 'Upload CV', bn: 'সিভি আপলোড' },
      step4: { en: 'Upload NID', bn: 'এনআইডি আপলোড'},
      step5: { en: 'Review', bn: 'পর্যালোচনা' },
      fullName: { en: 'Name', bn: 'নাম' },
      phone: { en: 'Mobile Number', bn: 'মোবাইল নম্বর' },
      address: { en: 'Full Address', bn: 'সম্পূর্ণ ঠিকানা' },
      uploadAvatar: { en: 'Upload Profile Photo', bn: 'প্রোফাইল ছবি আপলোড করুন' },
      selectSkills: { en: 'Work Experienced in', bn: 'কাজের অভিজ্ঞতা' },
      selectCoverage: { en: 'Preferred Area (within Metropolitan)', bn: 'পছন্দের এলাকা (মেট্রোপলিটনের মধ্যে)' },
      uploadCV: { en: 'Upload Your CV/Resume', bn: 'আপনার সিভি/রিজিউম আপলোড করুন' },
      cvHelper: { en: 'Please upload your CV in PDF format. This will help us verify your experience.', bn: 'দয়া করে আপনার সিভি PDF ফরম্যাটে আপলোড করুন। এটি আমাদের আপনার অভিজ্ঞতা যাচাই করতে সাহায্য করবে।' },
      uploadNID: { en: 'Upload Your NID Card', bn: 'আপনার এনআইডি কার্ড আপলোড করুন' },
      nidHelper: { en: 'Please upload a clear photo of your National ID card. This is required for verification.', bn: 'দয়া করে আপনার জাতীয় পরিচয়পত্রের একটি স্পষ্ট ছবি আপলোড করুন। এটি যাচাইকরণের জন্য প্রয়োজন।' },
      fileSelected: { en: 'File Selected:', bn: 'ফাইল নির্বাচিত:' },
      submitApplication: { en: 'Submit Application', bn: 'আবেদন জমা দিন' },
      applicationSubmitted: { en: 'Application Submitted!', bn: 'আবেদন জমা দেওয়া হয়েছে!' },
      submissionMessage: { en: 'Thank you for applying. We will review your application and get back to you within 3-5 business days.', bn: 'আবেদন করার জন্য ধন্যবাদ। আমরা আপনার আবেদন পর্যালোচনা করব এবং ৩-৫ কার্যদিবসের মধ্যে আপনার সাথে যোগাযোগ করব।' },
      close: { en: 'Close', bn: 'বন্ধ করুন' },
      voterIdNumber: { en: 'Voter ID Card Number', bn: 'ভোটার আইডি কার্ড নম্বর' },
      experienceYears: { en: 'Experience (Years)', bn: 'অভিজ্ঞতা (বছর)' },
      gmailAddress: { en: 'Gmail Address (if any)', bn: 'জি-মেইল ঠিকানা (যদি থাকে)' },
      hasSmartphone: { en: 'Do you have a smart mobile?', bn: 'আপনার কি স্মার্ট মোবাইল আছে?' },
      hasBikeOrCycle: { en: 'Do you have a bike/cycle?', bn: 'আপনার কি বাইক/সাইকেল আছে?' },
      yes: { en: 'Yes', bn: 'হ্যাঁ' },
      no: { en: 'No', bn: 'না' },
  },
  authPage: {
    title: { en: 'Login or Create an Account', bn: 'লগইন করুন বা একটি অ্যাকাউন্ট তৈরি করুন' },
    subtitle: { en: 'Enter your phone number to get started.', bn: 'শুরু করতে আপনার ফোন নম্বর লিখুন।' },
    phonePlaceholder: { en: 'Phone Number (e.g., 01712345678)', bn: 'ফোন নম্বর (যেমন, ০১৭১২৩৪৫৬৭৮)' },
    continue: { en: 'Continue', bn: 'চালিয়ে যান' },
    otpTitle: { en: 'Enter Verification Code', bn: 'যাচাইকরণ কোড লিখুন' },
    otpSubtitle: { en: 'We sent a 4-digit code to', bn: 'আমরা একটি ৪-ডিজিটের কোড পাঠিয়েছি' },
    otpPlaceholder: { en: '4-Digit Code', bn: '৪-ডিজিটের কোড' },
    verify: { en: 'Verify', bn: 'যাচাই করুন' },
    signupTitle: { en: 'Complete Your Profile', bn: 'আপনার প্রোফাইল সম্পূর্ণ করুন' },
    signupSubtitle: { en: 'Just a few more details to create your account.', bn: 'আপনার অ্যাকাউন্ট তৈরি করতে আরও কয়েকটি বিবরণ প্রয়োজন।' },
    namePlaceholder: { en: 'Your Full Name', bn: 'আপনার পুরো নাম' },
    addressPlaceholder: { en: 'Your Full Address', bn: 'আপনার সম্পূর্ণ ঠিকানা' },
    createAccount: { en: 'Create Account', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  },
  chatbot: {
    greeting: { en: 'Hi there! How can I help you today?', bn: 'হাই! আমি আপনাকে আজ কিভাবে সাহায্য করতে পারি?' },
    options: {
        booking: { en: 'Check a booking', bn: 'বুকিং চেক করুন' },
        payment: { en: 'Payment issue', bn: 'পেমেন্ট সমস্যা' },
        other: { en: 'Something else', bn: 'অন্য কিছু' },
    },
    bookingPrompt: { en: 'Sure! Please enter your Booking ID (e.g., FIXBD-ABC123).', bn: 'অবশ্যই! অনুগ্রহ করে আপনার বুকিং আইডি লিখুন (যেমন, FIXBD-ABC123)।' },
    paymentInfo: { en: 'For payment issues, please contact our support at support@fixbd.com. We accept bKash, Nagad, and Card.', bn: 'পেমেন্ট সংক্রান্ত সমস্যার জন্য, অনুগ্রহ করে আমাদের সাপোর্টে যোগাযোগ করুন support@fixbd.com এ। আমরা বিকাশ, নগদ এবং কার্ড গ্রহণ করি।' },
    otherInfo: { en: 'For any other questions, please call our helpline at 16XXX or email support@fixbd.com.', bn: 'অন্য কোনো প্রশ্নের জন্য, অনুগ্রহ করে আমাদের হেল্পলাইন 16XXX এ কল করুন বা support@fixbd.com এ ইমেল করুন।' },
    invalidBooking: { en: 'Sorry, I could not find a booking with that ID. Please double-check.', bn: 'দুঃখিত, আমি এই আইডিসহ কোনো বুকিং খুঁজে পাইনি। অনুগ্রহ করে আবার চেক করুন।' },
    bookingStatus: { en: 'Booking status for', bn: 'এর জন্য বুকিং স্ট্যাটাস' },
    is: { en: 'is', bn: 'হলো' },
    needMoreHelp: { en: 'Do you need more help?', bn: 'আপনার কি আরও সাহায্য দরকার?' },
    yes: { en: 'Yes', bn: 'হ্যাঁ' },
    no: { en: 'No, thanks!', bn: 'না, ধন্যবাদ!' },
    anythingElse: { en: 'How else can I help?', bn: 'আমি আর কিভাবে সাহায্য করতে পারি?' },
  },
  bookingTracker: {
    title: { en: 'Track Your Booking', bn: 'আপনার বুকিং ট্র্যাক করুন' },
    backToBookings: { en: 'Back to My Bookings', bn: 'আমার বুকিং-এ ফিরে যান' },
    statusPlaced: { en: 'Booking Placed', bn: 'বুকিং করা হয়েছে' },
    statusPlacedDesc: { en: 'We have received your request and are finding a professional.', bn: 'আমরা আপনার অনুরোধ পেয়েছি এবং একজন পেশাদার খুঁজছি।' },
    statusAssigned: { en: 'Professional Assigned', bn: 'পেশাদার নিযুক্ত' },
    statusAssignedDesc: { en: 'Our team has matched you with a verified professional who will contact you shortly.', bn: 'আমাদের টিম আপনাকে একজন যাচাইকৃত পেশাদারের সাথে মিলিয়ে দিয়েছে যিনি শীঘ্রই আপনার সাথে যোগাযোগ করবেন।' },
    statusInProgress: { en: 'Work In Progress', bn: 'কাজ চলছে' },
    statusInProgressDesc: { en: 'Your service is currently being performed by the professional.', bn: 'আপনার পরিষেবা বর্তমানে পেশাদার দ্বারা সঞ্চালিত হচ্ছে।' },
    statusCompleted: { en: 'Service Completed', bn: 'পরিষেবা সম্পন্ন' },
    statusCompletedDesc: { en: 'The job is done! Please rate your experience.', bn: 'কাজ সম্পন্ন হয়েছে! আপনার অভিজ্ঞতা রেট করুন।' },
    delayInfo: { en: 'Delayed', bn: 'বিলম্বিত' }
  }
};

export const VENDOR_SUBSCRIPTION_PLANS: { [key: string]: VendorSubscription } = {
    basic: { planName: 'Basic', commissionRate: 0.20, monthlyFee: 0 },
    pro: { planName: 'Pro', commissionRate: 0.12, monthlyFee: 999 },
};

export const CUSTOMER_SUBSCRIPTION_PLANS: { [key: string]: CustomerSubscription } = {
    plus_premium: { planName: 'FixBD Plus Premium', status: 'Active', nextBillingDate: new Date(), discountRate: 0.10 },
};

export const WHY_CHOOSE_US_POINTS = [
    { Icon: ShieldCheckIcon, title: { en: 'Trusted & Verified Pros', bn: 'বিশ্বস্ত এবং যাচাইকৃত প্রো' }, description: { en: 'All our partners undergo rigorous background checks and training.', bn: 'আমাদের সকল অংশীদার কঠোর ব্যাকগ্রাউন্ড চেক এবং প্রশিক্ষণের মধ্য দিয়ে যায়।' } },
    { Icon: PriceTagIcon, title: { en: 'Transparent Pricing', bn: 'স্বচ্ছ মূল্য নির্ধারণ' }, description: { en: 'Know the price upfront. No hidden charges, ever.', bn: 'আগেই দাম জানুন। কোনো লুকানো চার্জ নেই, কখনোই না।' } },
    { Icon: ClockIcon, title: { en: 'On-Time Service', bn: 'সময়মত পরিষেবা' }, description: { en: 'We value your time. Our professionals arrive as scheduled.', bn: 'আমরা আপনার সময়কে মূল্য দিই। আমাদের পেশাদাররা নির্ধারিত সময়ে পৌঁছায়।' } },
    { Icon: HeadsetIcon, title: { en: 'Dedicated Support', bn: 'ডেডিকেটেড সাপোর্ট' }, description: { en: 'Our customer support team is always here to help you.', bn: 'আমাদের গ্রাহক সহায়তা দল আপনাকে সাহায্য করার জন্য সর্বদা এখানে রয়েছে।' } },
];

export const TESTIMONIALS = [
    { name: 'Rahim Ahmed', location: 'Dhaka', quote: { en: 'The electrician from FixBD was very professional and fixed the issue in no time. Highly recommended!', bn: 'FixBD-এর ইলেকট্রিশিয়ান খুব পেশাদার ছিলেন এবং অল্প সময়ের মধ্যেই সমস্যাটি সমাধান করেছেন। অত্যন্ত প্রস্তাবিত!' } },
    { name: 'Fatima Chowdhury', location: 'Chittagong', quote: { en: 'Booking an AC service was so easy. The team was punctual and did a thorough cleaning. My AC works like new!', bn: 'এসি সার্ভিস বুক করা খুব সহজ ছিল। দলটি সময়নিষ্ঠ ছিল এবং পুঙ্খানুপঙ্খভাবে পরিষ্কার করেছে। আমার এসি নতুনের মতো কাজ করছে!' } },
    { name: 'Sultan Khan', location: 'Sylhet', quote: { en: 'I used their plumbing service for a leak. The response was quick, and the plumber was very skilled. Great service!', bn: 'আমি একটি লিকেজের জন্য তাদের প্লাম্বিং পরিষেবা ব্যবহার করেছি। প্রতিক্রিয়া দ্রুত ছিল, এবং প্লাম্বার খুব দক্ষ ছিলেন। দারুণ সেবা!' } },
];

export const TIME_SLOTS: { id: TimeSlot; label: LocalizedString }[] = [
  { id: TimeSlot.Morning, label: { en: 'Morning (9am - 12pm)', bn: 'সকাল (৯টা - ১২টা)' } },
  { id: TimeSlot.Afternoon, label: { en: 'Afternoon (1pm - 5pm)', bn: 'বিকাল (১টা - ৫টা)' } },
  { id: TimeSlot.Evening, label: { en: 'Evening (6pm - 9pm)', bn: 'সন্ধ্যা (৬টা - ৯টা)' } },
];